### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ThisIsRobokitty** [ThisIsRobokitty/cst336-lab3#21]
Have fun. Make sure the two buttons are at the bottom ( or maybe side ).

**Comment by GarredMurphy** [comment]
I will start working on in right now

**Comment by GarredMurphy** [comment]
I may have questions though.  Can we see each other on campus.  If I run into any problems I would like to have somebody to do this with me

**Comment by ThisIsRobokitty** [comment]
I won't be reachable until 10 minutes before class. I can recommend something to you though. Remove `top:75px;
        left:522px;
        position:absolute;` from the `input` tag. 

Here's a good list to do:
1) Center all <p> tags
2) Center all images
3) space images equally with margin if possible.
4) The player icon has custom id `icon`
5) The cards have custom id `card`
6) the custom tags are not in the css file, you'll have to add them. 
7) anchor the `input` tags so the buttons move to the bottom.

**Comment by GarredMurphy** [comment]
I am not sure if I know how to do all of those things but I will try to do them.  I don't remember the css rules that we were taught in class very well, but I will try to do your suggestions.  Also, I will add a player image for myself and a placeholder for diego

**Comment by ThisIsRobokitty** [comment]
Excellent. Here's more tips:
Steps for committing:

Step 1: If you have not updated your master branch, do that now. 
=> `cd /projectdirectory`
Should now read `~/workspace/cst336-lab3 (master)` or `~/workspace/cst336-lab3 (garred)`
If in `(master)`, skip to step 2, if in `(garred)` do the following:
=> `git checkout master`
=> `git pull`

Step 2: Change back to your branch
=> `git checkout garred`
You can now work at this point

Step 3: Committing changes
do the following
=> `git add .`
=> `git commit -m "comments here"`

Step 4: Pushing
=> `git push`
And that's it. If you want to take it a step further, make a push request on github on the branches page for your branch. I'll check it in the morning.

Remember, google is your friend. A note on the CSS, refer back to other labs or assignments if possible.
Quick reference:
css id = `#cssID`, `#main`, `#card`, `#icon`, `#playrow`
css tag = `input`, `body`, `img`, `form`, `div`, `p`

https://www.w3schools.com/css/css_examples.asp   //some good samples

A quick important example

`img {
    //css
}`   affects all images on the page
`img#card {
     //css
}`  affects only images with the `#card` id

**Comment by GarredMurphy** [comment]
it is now 5 AM, I have not yet pushed any changes to my branch.

**Comment by GarredMurphy** [comment]
it is now past 6 PM.  I still have not pushed any changed to my branch.  I am been working on adding CSS rules, and I also have added a few things to the page.  I have also corrected a few small mistakes in the code that were not noticed before.  For example, there were places where "id" was used when "class" should have been used.

**Comment by GarredMurphy** [comment]
The website now looks way better than it did before.  it still needs some work, but I am making progress

**Comment by GarredMurphy** [comment]
I think that their is an error in how the game determines the winner and the final score.  I will probably make that the last thing I fix.

**Comment by GarredMurphy** [comment]
I think it now has enough CSS rules now.  I am going to work on fixing the arrangement of the objects on the page and fixing the mistakes in the game.

**Comment by GarredMurphy** [comment]
I just pushed a bunch of changes to my branch.  it includes a bunch of additions to css and several glitch fixes and adjustments to the other files.

**Comment by ThisIsRobokitty** [comment]
Good work, the site looks great. I'll be merging your changes now.

**Comment by GarredMurphy** [comment]
I actually am not finished with CSS yet.  The header, the card table and the buttons need to be moved a little bit more.  they don't look right currently

**Comment by ThisIsRobokitty** [comment]
Ok. Great work so far.

**Comment by GarredMurphy** [comment]
I pushed in last time.  I think I am finished now.  please add my changes to master
