### ISSUE TITLE
checkWin

### ISSUE THREAD

**Issue by GarredMurphy** [ThisIsRobokitty/cst336-lab3#23]
The checkWin() function does not work correctly.  I have noticed that the winner is always the second player and the points that are displayed in the winning message are wrong.  I am trying to fix it but it would be a good idea if we all worked on this just in case I can't do it.

**Comment by GarredMurphy** [comment]
I think I have figured out what the problem is.  the program was not correctly pushing something to an array.  it was it only pushing one value when it should have been pushing several.

**Comment by GarredMurphy** [comment]
I am now pushing a new version to my branch with the checkWin() function corrected.  please take a look at it and let me know if it seems completely fixed or if you think it should be changed furthing

**Comment by GarredMurphy** [comment]
I pushed the a new version to my branch again.  merge it with the master branch again

**Comment by ThisIsRobokitty** [comment]
Will do.

**Comment by GarredMurphy** [comment]
I am going to work on the css now.  do you think the checkWin() needs further work or is it doing what it should do now?  Is the final score it displays supposed to be the total score off all four players added together or is that a mistake?  Should we add a check to make sure that it isn't possible for nobody to win due to all the scores going over 42?  Are the conditions for winning even correct?  I don't know how this game works.

**Comment by ThisIsRobokitty** [comment]
The winning score is calculated correctly, but it assigns it to the wrong name. Probably and array issue or something. I'll figure it out.

**Comment by GarredMurphy** [comment]
I already fixed that.  it should be showing the correct name.

**Comment by GarredMurphy** [comment]
I just pushed another update to my branch.  I think we are almost finished.

**Comment by GarredMurphy** [comment]
I think I am finished now.  please add my changes to master.

**Comment by GarredMurphy** [comment]
i was wrong.  i looked at the rules for the game and i now see that the way the game chooses the winner is incorrect.  currently it the winner is the player with the highest score after any player gets a score between 37 and 42.  this is wrong.  it needs more work

**Comment by GarredMurphy** [comment]
I think I have it fixed.  I have not pushed the final version yet.  I will finish testing it and then i will push it to my branch.

**Comment by GarredMurphy** [comment]
I fixed it.  we need to submit it now.

**Comment by ThisIsRobokitty** [comment]
I put a link on ilearn
